### ISSUE TITLE
Why does the Entrypoint revert if the sender's wallet has already been deployed?

### ISSUE THREAD

**Issue by derekchiang** [eth-infinitism/account-abstraction#115]
Apologies if this is not the right place to ask this question, but I had a question about the spec.

According to [the spec](https://github.com/eth-infinitism/account-abstraction/blob/699ecca1770f7e561bbc01e4e15e30ce2a50ebcb/eip/EIPS/eip-4337.md?plain=1#L446-L447), if `initCode` is included in `UserOp` and the sender address already has a contract deployed, the operation aborts.

I'm not sure if I understand the rationale for this design decision.  In my opinion, it seems to be more user-friendly if the EntryPoint proceeds even if there's already a contract deployed.  The reason is that this would simplify client code: the client can safely include `initCode`, without knowing if the contract has already been deployed.  With the current spec, the client would have to query the blockchain to check if the sender has already been deployed, which places extra burden on the client.

If the concern is with efficiency (namely that `calldata` gets larger if `initCode` is always included), the client is still totally free to query the blockchain and NOT include `initCode` if the sender has already been deployed, just like today.  Basically, it seems to me that allowing the EntryPoint to proceed improves client UX while still giving clients the option to optimize for efficiency (by not including `initCode` on every call) should they so choose.

**Comment by drortirosh** [comment]
The reason is that we try to be as strict as possible on execution, and not ignore something only because it "already exists".
Also, while its true that usually the client pays for this extra calldata, if there is a paymaster, it becomes the paymaster's problem to pay for extra info that is not in use.
The client is required to query the account's on-chain status, even if only to query for the current nonce value, so there is no real issue for it also to determine if initCode was already deployed, and thus not required to be put again.
