### ISSUE TITLE
Unreasonable onchain gas calculation and verification

### ISSUE THREAD

**Issue by Mobius3-3** [eth-infinitism/account-abstraction#174]
In ```EntryPoint.sol``` contract file, two logics in ```_validatePrepayment``` seem unreasonable.

1. When calculating required gas, ```verificationGasLimit * 3``` is the required gas for verification if there is a paymaster. While, the upper limit for actual gas used is verificationGasLimit. These two parts are not aligned.
2. Calculation of actual gas used includes ```preVerificationGas``` which is not verified on chain, but it's possible to cause over or under estimation of preRequired or actualUsed gas. <br>

(The position of code is marked by comments)

```solidity
unchecked {
        uint256 gasUsed = preGas - gasleft();
        // Issue1: not aligned with verificationGasLimit * 3 when calculating required gas 
        if (userOp.verificationGasLimit < gasUsed) {
            revert FailedOp(opIndex, mUserOp.paymaster, "AA40 over verificationGasLimit");
        }
        outOpInfo.prefund = requiredPreFund;
        outOpInfo.contextOffset = getOffsetOfMemoryBytes(context);
        // Issue2: preVerificationGas is not verified onchain but it's possible to cause over or under estimation of preRequired or actualUsed gas
        outOpInfo.preOpGas = preGas - gasleft() + userOp.preVerificationGas;
    }
```

**Comment by drortirosh** [comment]
Thank you for looking into the code...
specifically:
1. verificationGas has double use: First, it is the limit of the validation (should cover creation+account.validateUserOp + paymaster.validatePaymasterUserOp). The second usage is as the gas-limit for `paymaster.postOp()` (simply because we didn't want to introduce yet another parameter just for this case). 
 The `postOp()` itself is called only if the paymaster returns a context, but we check the gas limits before we call the paymaster's validation, so we require the maximum payment to be able to cover for it.
  If postOp() itself is interesting, in that it can be called **twice**: If it reverts inside the innerHandleOp, it reverts itself (and the account's execution method), and then called again in the outer context. For this reason, if there is a paymaster we require 3*verificationGas.
2. `preVerificationGas` comes to compensate for extra costs that can't be calculated on-chain. it is calculated (and signed by) by the calling user, and then the bundler validates this value is enough before including in a bundle. 
   So neither can attempt to grief the other. 
   The one entity that can be griefed this way is a **paymaster**. So a paymaster should bound this value, and reject a request with infeasible value (unless this is a TokenPaymaster, which uses the calling user's funds to pay for the request)

**Comment by Mobius3-3** [comment]
thank you for elaborating the tradeoffs why it's designed in that way. Now it makes sense!

**Comment by Mobius3-3** [comment]
> Thank you for looking into the code... specifically:
> 
> 1. verificationGas has double use: First, it is the limit of the validation (should cover creation+account.validateUserOp + paymaster.validatePaymasterUserOp). The second usage is as the gas-limit for `paymaster.postOp()` (simply because we didn't want to introduce yet another parameter just for this case).
>    The `postOp()` itself is called only if the paymaster returns a context, but we check the gas limits before we call the paymaster's validation, so we require the maximum payment to be able to cover for it.
>    If postOp() itself is interesting, in that it can be called **twice**: If it reverts inside the innerHandleOp, it reverts itself (and the account's execution method), and then called again in the outer context. For this reason, if there is a paymaster we require 3*verificationGas.
> 2. `preVerificationGas` comes to compensate for extra costs that can't be calculated on-chain. it is calculated (and signed by) by the calling user, and then the bundler validates this value is enough before including in a bundle.
>    So neither can attempt to grief the other.
>    The one entity that can be griefed this way is a **paymaster**. So a paymaster should bound this value, and reject a request with infeasible value (unless this is a TokenPaymaster, which uses the calling user's funds to pay for the request)

thank you for elaborating the tradeoffs why it's designed in that way. Now it makes sense!
