### ISSUE TITLE
Clarification of storage access

### ISSUE THREAD

**Issue by jamesmccomish** [eth-infinitism/account-abstraction#249]
I would like to clarify what is permitted in the validation steps wrt storage access.

In the **Storage associated with an address** section it seems to suggest that mappings where the key is the sender are allowed to be read:
`We define storage slots as “associated with an address” as all the slots that uniquely related on this address, and cannot be related with any other address. In solidity, this includes all storage of the contract itself, and **any storage of other contracts that use this contract address as a mapping key**.`

In the **Rational** section it doesn't mention this:
`In this proposal, we expect accounts to have a validateUserOp method that takes as input a UserOperation, and verify the signature and pay the fee. This method is required to be almost-pure: it is **only allowed to access the storage of the account itself,** cannot use environment opcodes (eg. TIMESTAMP), and **can only edit the storage of the account**, and can also send out ETH (needed to pay the entry point).`

I'm wondering if it has just not been mentioned the second time, or if external storage locations set to the sender address are actually not allowed.

**Comment by drortirosh** [comment]
The rationale section should be clarified.
We try to prevent shared storage between different userops, so we make sure each one uses storage related to the account only: that is, the account's storage, and storage cells that are associated with it (e.g. balances)
Since we don't allow multiple userops of the same account in a bundle, the above rule also means that userops don't have a shared storage.
