### ISSUE TITLE
validateUserOp cant read another contract slot

### ISSUE THREAD

**Issue by algtm** [eth-infinitism/account-abstraction#268]
My wallet use RSA verification, each user shares the same public key,so an additional contract is needed to store the public key. This caused validateUserOp to read a slot from another contract and rejected by bundler. How can this pattern work with 4337?

**Comment by drortirosh** [comment]
sharing data between UserOps is not allowed, since it opens the bundlers to a DoS attack. 
Each UserOp may access data related to its own account ("sender").
This data is either the storage of this specific account, or storage in another contract, that is indexed by the account address (e.g token balance).
