### ISSUE TITLE
Account Factory Implementation

### ISSUE THREAD

**Issue by alexTwo3** [eth-infinitism/account-abstraction#269]
Looking through the samples I see that the Simple Account and Simple Account Factory are implemented using UUPS Upgradable.
Would this not then require a large amount of transactions to update all the accounts when a Wallet upgrade is needed.
A beacon proxy implementation would use more gas on a per call rate, but would cost less for each Account deployed.
Would a beacon proxy implementation not be more suited for an account factory?

**Comment by drortirosh** [comment]
1. Beacon can't be used, since it is a reference to external contract. during validation, an account should use only its own storage.
2. A beacon could also cause a "mass invalidation": a large # of useroperations that can be invalidated with a single "flip" of a storage - the beacon address (this is actually why (1) above is not permitted)
3. Usability-wise, each account should decide for itself if and when to upgrade, without a central service to enforce it.
4. The upgrade requires setting a new "implementation" for the account - is that such a huge overhead (of course, it costs per each account separately, as I explained above)
