### ISSUE TITLE
Token paymaster storage access restriction 

### ISSUE THREAD

**Issue by huaweigu** [eth-infinitism/account-abstraction#272]
Thanks a lot for the nice work you've contributed to the community!

`transferFrom` is usually guarded by modifiers like [whenNotPaused](https://github.com/centrehq/centre-tokens/blob/master/contracts/v1/Pausable.sol#L54) or others that [may need storage access](https://github.com/centrehq/centre-tokens/blob/master/contracts/v1/Pausable.sol#LL49C1-L49C1) into ERC20 token contract. Is that considered as forbidden storage access if the paymaster calls `transferFrom` in `validatePaymasterUserOp`? If so, is there any workaround?

If we call `transferFrom` in `postOp` (execution) then we wouldn't have this problem, but are there any other better options if we want to continue exploring the possibility of doing it in validation as recommended by 4337 team? 

Thanks to @hazim-j who proposed having an alternative (non canonical) mempool as a potential option. But I'm also wondering if we could consider relaxing the storage rule for specific access patterns (e.g. guarded `transferFrom`) without harming the other entities in the system.

Thank you in advance!

**Comment by yoavw** [comment]
Hi @huaweigu 

The problem with relaxing the rules is that it seems impossible to distinguish the legitimate case from an attack vector.  In the above example, [pauser](https://github.com/centrehq/centre-tokens/blob/0d3cab14ebd133a83fc834dbd48d0468bdf0b391/contracts/v1/Pausable.sol#L63) (or admin, who can [set](https://github.com/centrehq/centre-tokens/blob/0d3cab14ebd133a83fc834dbd48d0468bdf0b391/contracts/v1/Pausable.sol#L86) pauser) would be able to perform a DoS attack against the mempool:
1. Send 10000 UserOps with validation that performs transferFrom.
2. Call [pause](https://github.com/centrehq/centre-tokens/blob/0d3cab14ebd133a83fc834dbd48d0468bdf0b391/contracts/v1/Pausable.sol#L70), pausing the token for a few blocks, causing all the bundlers to drop these previously-valid UserOps, then unpause.

The access pattern of a guraded `transferFrom` seems indistinguishable from a malicious pattern where a single slot controlled by an attacker can invalidate an unbound number of UserOps.  Do you see a way to distinguish between the legitimate case and an attack vector, without whitelisting a specific known contract?

The general protocol can't trust any particular contract not to perform an attack, but a group of bundlers definitely can.  The contract could be audited to show that it's actually safe, or that an attack is unlikely (e.g. no one is going to pause USDC just to momentarily DoS the bundlers).  Therefore @hazim-j is right that the way to relax contract-specific rules is to add an alt mempool to bundlers that trust it.  E.g. whitelist this access pattern for a list of popular token contracts that are unlikely to be paused.

A bundler can participate in any number of such mempools in addition to the canonical one, but should only add mempools that it trusts not to open such attack vectors.  If all the bundlers read an audit report and agree that a certain contract is safe for whitelisting a certain access pattern, then this alt mempool becomes de facto canonical pool because all the bundlers join it.

If you see a better way to support this at the protocol level without resorting to an alt mempool, we're happy to discuss.

**Comment by huaweigu** [comment]
Hi @yoavw, thank you for prompt response. Agreed an alt mempool might be a good start. The same mempool could become de facto canonical mempool via auditing/voting over time. Similar process can probably also apply to pricing oracles in the future.

**Comment by yoavw** [comment]
No voting is needed.  Each bundler can participate in any number of alt mempools (in addition to the canonical one) as long as it trusts their conditions.  There's no need for consensus on any mempool except the canonical one, they just become bigger and more effective as more bundlers add them.

Personally I hope bundlers operators will be careful and not add things like pricing oracles without careful evaluation of the risk involved, since the operator of such oracle will be able to DoS them easily.  But it's really up to the bundler operators to decide on the risk level they're comfortable with.
