### ISSUE TITLE
pre-eip-155 transactions not supported

### ISSUE THREAD

**Issue by aymentrosh** [eth-infinitism/account-abstraction#372]
I'm trying to deploy account abstraction contracts to an op stack chain and I'm receiving this 
```
Error: ERROR processing /home/aymen/testriskharbor/karak/account-abstraction/deploy/1_deploy_entrypoint.ts:
Error: legacy pre-eip-155 transactions not supported (error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```
Does anyone know how can I disable the pre-eip-155 transactions because op stack doesn't support that

**Comment by drortirosh** [comment]
The standardized EntryPoint address and the accounts deployer assumes the [deterministic deployer](https://github.com/Arachnid/deterministic-deployment-proxy) is available on the network.
This, however, requires a one-time "non-eip155" transaction to get deployed. This is a cross-chain transaction so that the deployer itself (And any contracts it later deploys) will end up at the same address.

For some chains (e.g. mainnet, polygon), it was deployed before EIP-155 was added
For others (such as Base), it was accepted by the network, even that the network doesn't support non-EIP-155 transaction in general.

While ERC-4337 can work without it, all our standard tooling and testing do expect this standard deployer.

**Comment by aymentrosh** [comment]
If there's any way to deploy without changing the chain to support pre-eip-155 transactions?

**Comment by drortirosh** [comment]
no. eip-155 prevents deploying TXs that are not chain-specific (the txhash includes the chain-id)
the cross-chain deterministic deployer is, by design, using the same transaction across chains, so that it generates the same code (the txs are the same and even carry the same gas price (100gwei) - which might be considered too high or too low on some networks.

**Comment by aymentrosh** [comment]
the issue was fixed after enabling pre-eip-155 transactions on op-geth
