### ISSUE TITLE
[N17] Excessive code optimization

### ISSUE THREAD

**Issue by drortirosh** [eth-infinitism/account-abstraction#39]
In the UserOperation contract, the getSender function takes a UserOperation struct as input and returns the sender field of the struct using inline assembly code. This is the only struct member that has its own custom getter function, and even though there are two addresses in the struct ( sender and paymaster), only this one has a getter function. It is recommended to avoid using inline assembly because in general it is less safe and error-prone. In this particular instance, the code works because sender is the first item in the UserOperation struct, but if the sender variable position in the struct were to change, this code would break.
For safety and clarity, consider removal of the getSender function.

**Comment by drortirosh** [comment]
referencing struct fields are unexpectedly very expensive in solidity... `getSender()` saves ~800 gas per request (compared to using `userOp.sender` directly.
We did want to optimize all fields, but referencing the offsets using numeric values is indeed terrible, so we settled on optimizing just the first field.
Currently, there doesn't seem an enthusiasm in the solidity team to optimize this code.

**Comment by yoavw** [comment]
I also wasn't very happy with this optimization since the struct might change in the future, breaking this code if we don't pay attention.  But for 800 gas per request it's worth doing - carefully.  Maybe we should add an explicit test, filling the struct and verifying that getSender() returns the correct value.  I know we have other tests that will fail if we ever prepend something in this struct, but an explicit test would immediately highlight the problem.
