### ISSUE TITLE
`VerifyingPaymaster.sol._validatePaymasterUserOp()` does not correctly handle shortened signatures

### ISSUE THREAD

**Issue by Rassska** [eth-infinitism/account-abstraction#444]
### Description
- After an OZ upgrade here: #384 , it seems that the 64 bytes long signatures are not supported, since `_validatePaymasterUserOp()` does not invoke `ECDSA.recover(bytes32, bytes32, bytes32)`, but instead calls `ECDSA.recover(bytes32, bytes)`, which reverts in `ECDSA.tryRecover(bytes32, bytes)`. 

### Recommendation steps
- For 65 bytes long use `ECDSA.recover(bytes32, bytes)`
- For 64 bytes long use `ECDSA.recover(bytes32, bytes32, bytes32)`

**Comment by drortirosh** [comment]
This is a sample paymaster. you may use your own, using different signature.
We'd accept PRs to fix.
(btw: isn't there a single `recover` method that accept all supported signature lengths?)

**Comment by drortirosh** [comment]
I'm not sure we're going to fix it - probably just remove the specific length test in the VerifyingPaymaster, and let openzeppelin's ECDSA library to handle the signature.
Apparently, 64-byte signature was removed from the default handling of signature due to a possible security issue.
The VerifyingPaymaster is a sample contract, and of course you may modify it at will for your own purposes - but please make sure to audit your contracts.

**Comment by Rassska** [comment]
> I'm not sure we're going to fix it - probably just remove the specific length test in the VerifyingPaymaster, and let openzeppelin's ECDSA library to handle the signature. Apparently, 64-byte signature was removed from the default handling of signature due to a possible security issue. The VerifyingPaymaster is a sample contract, and of course you may modify it at will for your own purposes - but please make sure to audit your contracts.

I do agree, we found it during the review in one of the project

**Comment by Tomicubero5** [comment]
No sé cómo funciona
